FROM python:3.14.2-alpine3.23@sha256:31da4cb527055e4e3d7e9e006dffe9329f84ebea79eaca0a1f1c27ce61e40ca5

COPY worker.py /opt/legalforecast/container-runtime-worker.py

ENTRYPOINT ["python", "-I", "-u", "/opt/legalforecast/container-runtime-worker.py"]
